# Generated by Django 5.2.11 on 2026-05-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatmessage_chatsession_remove_conversation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='tools_used',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
