# Generated by Django 5.2.11 on 2026-05-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatmessage_tools_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
