# Generated by Django 5.2.11 on 2026-09-30 08:48

import chatbot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_chatmessage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='access_key',
            field=models.CharField(default=chatbot.models.generate_access_key, editable=False, max_length=64),
        ),
    ]
