# Generated by Django 5.2.11 on 2026-09-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['room_type', 'date'], name='hotels_avai_room_ty_fb4b33_idx'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(condition=models.Q(('room_unit__isnull', True)), fields=('room_type', 'date'), name='uniq_availability_room_type_date'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(condition=models.Q(('room_unit__isnull', False)), fields=('room_unit', 'date'), name='uniq_availability_room_unit_date'),
        ),
    ]
