# Generated by Django 5.2.11 on 2026-05-05 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('all', 'All'), ('monument', 'Monument'), ('temple', 'Temple'), ('park', 'Park'), ('museum', 'Museum'), ('nature', 'Nature'), ('other', 'Other')], default='other', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('review_count', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('osm_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('osm_type', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attractions',
                'ordering': ['-rating', '-review_count'],
                'indexes': [models.Index(fields=['category'], name='attractions_categor_b26c08_idx'), models.Index(fields=['city'], name='attractions_city_89ff81_idx'), models.Index(fields=['latitude', 'longitude'], name='attractions_latitud_e38d54_idx'), models.Index(fields=['osm_id'], name='attractions_osm_id_1096d9_idx')],
            },
        ),
    ]
