# Generated by Django 5.2.11 on 2026-10-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='image_credit',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
