# Generated by Django 5.2.11 on 2026-02-25 19:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('node_type', models.CharField(choices=[('bus', 'Bus Stand'), ('auto', 'Auto Stand'), ('metro', 'Metro Station'), ('taxi', 'Taxi Stand')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
