# Generated by Django 5.2.11 on 2026-09-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportnode',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='transportnode',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='transportnode',
            name='image_credit',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='transportnode',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=600),
        ),
        migrations.AddField(
            model_name='transportnode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transportnode',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transportnode',
            name='operator',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='transportnode',
            name='osm_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transportnode',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='transportnode',
            name='route_refs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='transportnode',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transportnode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transportnode',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='transportnode',
            name='node_type',
            field=models.CharField(choices=[('bus', 'Bus Stand'), ('auto', 'Auto Stand'), ('metro', 'Metro Station'), ('rail', 'Railway Station'), ('airport', 'Airport'), ('taxi', 'Shared Taxi / Cab Stand'), ('ferry', 'Ferry Terminal'), ('other', 'Other')], default='bus', max_length=20),
        ),
        migrations.AddIndex(
            model_name='transportnode',
            index=models.Index(fields=['node_type'], name='transport_type_idx'),
        ),
        migrations.AddIndex(
            model_name='transportnode',
            index=models.Index(fields=['city'], name='transport_city_idx'),
        ),
        migrations.AlterModelTable(
            name='transportnode',
            table='transport_node',
        ),
    ]
