# Generated by Django 5.2.11 on 2026-02-25 19:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('monument', 'Monument'), ('temple', 'Temple'), ('park', 'Park'), ('museum', 'Museum'), ('nature', 'Nature'), ('other', 'Other')], default='other', max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('image', models.ImageField(blank=True, null=True, upload_to='attraction_images/')),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
