# Generated by Django 5.2.11 on 2026-05-06 05:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('all', 'All'), ('street_food', 'Street Food'), ('restaurant', 'Restaurant'), ('cafe', 'Café'), ('dhaba', 'Dhaba'), ('bakery', 'Bakery'), ('sweet_shop', 'Sweet Shop'), ('juice_bar', 'Juice Bar'), ('fast_food', 'Fast Food'), ('other', 'Other')], default='other', max_length=20)),
                ('cuisine', models.CharField(choices=[('north_indian', 'North Indian'), ('south_indian', 'South Indian'), ('chinese', 'Chinese'), ('mughlai', 'Mughlai'), ('punjabi', 'Punjabi'), ('rajasthani', 'Rajasthani'), ('bengali', 'Bengali'), ('gujarati', 'Gujarati'), ('continental', 'Continental'), ('italian', 'Italian'), ('street', 'Street Food'), ('multi', 'Multi-Cuisine'), ('other', 'Other')], default='other', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('review_count', models.IntegerField(default=0)),
                ('price_level', models.IntegerField(choices=[(1, '₹'), (2, '₹₹'), (3, '₹₹₹'), (4, '₹₹₹₹')], default=1)),
                ('avg_cost_for_two', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('is_veg', models.BooleanField(blank=True, null=True)),
                ('is_open_now', models.BooleanField(default=True)),
                ('home_delivery', models.BooleanField(default=False)),
                ('takeaway', models.BooleanField(default=False)),
                ('outdoor_seating', models.BooleanField(default=False)),
                ('osm_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('osm_type', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'food_places',
                'ordering': ['-rating', '-review_count'],
                'indexes': [models.Index(fields=['category'], name='food_places_categor_3788e0_idx'), models.Index(fields=['city'], name='food_places_city_d47093_idx'), models.Index(fields=['latitude', 'longitude'], name='food_places_latitud_65f141_idx'), models.Index(fields=['osm_id'], name='food_places_osm_id_058200_idx'), models.Index(fields=['cuisine'], name='food_places_cuisine_52562c_idx')],
            },
        ),
    ]
