# Generated by Django 5.2.6 on 2026-10-05 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('image_url', models.URLField(blank=True, default='')),
                ('is_veg', models.BooleanField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'food_menu_items',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='foodplace',
            name='image_credit',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='foodplace',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodplace',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_places', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foodplace',
            name='category',
            field=models.CharField(choices=[('street_food', 'Street Food'), ('restaurant', 'Restaurant'), ('cafe', 'Café'), ('dhaba', 'Dhaba'), ('bakery', 'Bakery'), ('sweet_shop', 'Sweet Shop'), ('juice_bar', 'Juice Bar'), ('fast_food', 'Fast Food'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddIndex(
            model_name='foodplace',
            index=models.Index(fields=['owner'], name='food_places_owner_i_df85ea_idx'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='food_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='food.foodplace'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['food_place'], name='food_menu_i_food_pl_1a370e_idx'),
        ),
    ]
