# Generated by Django 5.2.11 on 2026-09-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=32, unique=True)),
                ('last_settlement_index', models.IntegerField(default=0)),
                ('settlements_total', models.IntegerField(default=0)),
                ('places_total', models.IntegerField(default=0)),
                ('status', models.CharField(default='idle', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sync_state',
            },
        ),
        migrations.CreateModel(
            name='EnrichmentCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, default='', max_length=32)),
                ('found', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'enrichment_cache',
                'indexes': [models.Index(fields=['expires_at'], name='enrich_exp_idx')],
            },
        ),
    ]
