# Generated by Django 5.2.11 on 2026-09-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place_type', models.CharField(default='town', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('population', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('osm_id', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'settlement',
                'indexes': [models.Index(fields=['-population'], name='settlement_pop_idx'), models.Index(fields=['name'], name='settlement_name_idx')],
            },
        ),
    ]
